### ISSUE TITLE
Add piecepack pyramids to accessories

### ISSUE THREAD

**Issue by trevorld** [trevorld/piecepackr#37]
Piecepack pyramids have four faces (but sides the same, directional face and backs).  A top view would also be helpful in game diagrams.

http://www.ludism.org/ppwiki/PiecepackPyramids

Also create a configuration that supports Icehouse pieces.

http://www.wunderland.com/icehouse/MakingIcehouse.html
https://www.icehousegames.org/wiki/index.php?title=Zero-pip_pyramids

So support ``pyramid_face``, ``pyramid_back``, ``pyramid_side`` (or ``pyramid_left``, ``pyramid_right``?), and ``pyramid_top``.  Support seven sizes equivalent to 3 pips, 2.5 pips, 2.0 pips, 1.5 pips, 1 pips, 0.5 pips, 0 pips?

**Comment by trevorld** [comment]
Should actually measure the example Piecepack Pyramids, proportions may not be the same as with the Icehouse pieces.

**Comment by tinfoilhatter** [comment]
I think adding Piecepack Pyramids is a good idea. They're one of the most widely used expansions, and making blank ones then adding piecepackr chip stickers does not really work, because the chips are much bigger than many of the pyramids (among other reasons).

**Comment by tinfoilhatter** [comment]
You don't need to measure them. Just ask Tim Schutz. He knows the exact measurements.

**Comment by trevorld** [comment]
Thanks for letting me know that the "kite" shaped "chips" are too big for some of Piecepack pyramids (so I don't need to do that experiment myself).  I guess the "kite" shape is only good for custom d12's (i.e. Rainbow deck suit dice?).

**Comment by trevorld** [comment]
For the top view should be able to directly use ``pyramid_face``, ``pyramid_back``, etc. directly but with a short viewport so that they appear "squished".  May need to use a custom function #89 for ``pyramid_top`` though (but make it the default drawing function for ``pyramid_top`` instead of the basic generalized piecepack drawing function).

**Comment by trevorld** [comment]
Tim says biggest piecepack pyramid has a 7/8" base and smallest about a 1/4" base.  So bases of A=2/8", B=3/8", C=4/8", D=5/8", E=6/8", and F=7/8" seems reasonable.  Go up to a (non-standard) seventh rank gives you a 1" "G" base (same base as a 3-pip Icehouse piece).  In the PnP sheet five piecepack pyramids form a half-circle which implies pyramid peak triangle angle is 18 degrees and applying Law of Sines this implies that if a piecepack pyramid has a 1" base then it has an 1.538842" height (and 1.618034" longest edge) - this implies that a piecepack pyramid is a "shorter" pyramid than an Icehouse piece (1.75" height given 1" base).  So maybe implement ``pyramid_*`` and later implement ``icehouse_pyramid_*`` (although for rule diagrams could probably configure a "good enough" fake "ice house" pyramid with just piecepack pyramids)?

Lets implement both a ``pyramid_left`` and ``pyramid_right`` component_side (although default to the same rank symbol) in case people want to do playful things like put eye symbols on the front, a shield symbol on the left, and a sword on the right of their piecepack pyramids.
